local regex = {
	"^DLC_",
	"OBJ_BloodPotion_",
	"BOOK_",
	"TWN_TollCollector_",
	"_Destroyed$",
	"_REF$",
	"_Pact$",
	"_Rusty$",
	"_Dart$",
	"_Dart_%d*$",
	"_Sling$",
	"_Bonesaw$",
	"_FlameBlade$",
	"_FlameBlade_%d*$",
	"_ConjureElemental$",
	"_WildShape$",
	"_Myrmidon$",
}

local items = {
	"OBJ_FreezingSphere",
	"LOW_DeadMansSwitch_Shield",
	"MAG_OfTheShapeshifter_Mask",
	"LOW_RamazithsTower_Nightsong_Silver_Shield",
	"WPN_KingsKnife",
	"OBJ_Bomb_Orthon",
	"MAG_Hat_Circushat",
	"UND_MonkAmulet_Amulet",

	"OBJ_Scrolls_FindFamiliar",
	-- "OBJ_Scroll_BestowCurse",
	-- "OBJ_Scroll_AnimateDead",
	"OBJ_Scroll_Aid",
	"OBJ_Scroll_AnimalFriendship",
	"OBJ_Scroll_FlameBlade",
	"OBJ_Scroll_Goodberry",

	"WPN_LightCrossbow_Makeshift",
	"MAG_TheClover_Scimitar",
	"DEN_VoloOperation_ErsatzEye",
	"SHA_SharSpear",
	"MAG_Cunning_HandCrossbow",
	"MAG_Harpers_SingingSword",

	"ARM_Padded_Body",
	"ARM_StuddedLeather_Body",
	"ARM_Hide_Body",
	"ARM_ChainShirt_Body",
	"ARM_ScaleMail_Body",
	"ARM_Breastplate_Body",
	"ARM_HalfPlate_Body",
	"ARM_RingMail_Body",
	"ARM_ChainMail_Body",
	"ARM_Splint_Body",
	"ARM_Plate_Body",
	"ARM_Robe_Body",
	"ARM_Cloth_Body_1",
	"ARM_Cloth_Body_2",
	"ARM_Leather_Body_1",
	"ARM_Leather_Body_2",
	"ARM_Boots_Metal",
	"UNI_Astarion_StarterArmor",
	"ARM_Leather_Body_Druid",
	"ARM_Leather_Body_Rogue",
	"UNI_Daisy_Plate",
	"ARM_Gloves_Metal",
	"UNI_Daisy_Gloves",
	"UNI_Daisy_Boots",
	"UNI_GaleRobe",
	"ARM_Barbarian",
	"ARM_Bard",
	"ARM_Gloves_Leather",
	"ARM_Bracers_Barbarian",
	"ARM_Shoes",
	"ARM_Magic_Shoes",
	"ARM_Boots_Leather",
	"ARM_Hat",
	"ARM_Jester_Hat",
	"ARM_MerregonMask",
	"ARM_Helmet_Metal",
	"ARM_Circlet",
	-- "ARM_HeadbandOfIntellect",
	"UNI_ShadowheartCirclet",
	"ARM_Cloak",
	"ARM_Ring",
	"ARM_Amulet",
	"ARM_KeepsakeLocket_A",
	"ARM_Shield",
	"ARM_Shar_Shield",
	"ARM_Drow_Shield",
	-- "ARM_Toy_Shield",
	"ARM_Goblin_Shield_A",
	"ARM_Goblin_Shield_B",
	"ARM_Goblin_Shield_C",
	"ARM_Goblin_Shield_D",
	"ARM_Goblin_Shield_E",
	"ARM_Duergar_Shield_A",
	"ARM_Duergar_Shield_B",
	"ARM_KuoToa_Shield_A",
	"ARM_WoodWoad_Shield",
	"ARM_DEBUG_Ring_Strength",
	"ARM_DEBUG_Ring_Dexterity",
	"ARM_DEBUG_Ring_Constitution",
	"ARM_DEBUG_Ring_Intelligence",
	"ARM_DEBUG_Ring_Wisdom",
	"ARM_DEBUG_Ring_Charisma",
	"ARM_Instrument_Drum",
	"ARM_Instrument_Flute",
	"ARM_Instrument_Lute",
	"ARM_Instrument_Lyre",
	"ARM_Instrument_Violin",
	"ARM_Countercharm_Instrument_Drum",
	"ARM_Countercharm_Instrument_Flute",
	"ARM_Countercharm_Instrument_Lute",
	"ARM_Countercharm_Instrument_Lyre",
	"ARM_Countercharm_Instrument_Violin",
	"UNI_Karlach_StarterArmor",
	"UNI_Karlach_Shoes",
	"UNI_Karlach_Gloves",
	"UNI_Leather_Jaheira",
	"UNI_Jaheira_Gloves",
	"UNI_Jaheira_Boots",
	"GOB_DrowCommander_Leather_Gloves",
	"GOB_DrowCommander_Leather_Armor",
	"GOB_DrowCommander_Amulet",
	"GOB_DrowCommander_Mace",
	"ARM_Monk",
	"ARM_Padded_BGWatch",
	"ARM_Breastplate_BGWatch",
	"ARM_StuddedLeather_CultOfAbsolute",
	"ARM_Robe_CultOfAbsolute",
	"ARM_Civilian_Body",
	"ARM_Countercharm_Instrument_MusicBox",
	"ARM_Leather_Body_Drow",
	"ARM_DeathKnight_Shield",
	"ARM_Leather_Body_Minsc",
	"ARM_ScaleMail_FlamingFist",
	"ARM_Leather_FlamingFist",
	"ARM_HalfPlate_FlamingFist",
	"ARM_Robe_FlamingFist",
	"CRA_HermitCrab_Ring",
	"Quest_DEN_ARM_LuckyBoots",
	"DEN_Thiefling_Ring5",
	"Quest_Amulet_ConqueringGodPriest",
	"FOR_ShadowheartOM_SharCrown",
	"FOR_DeathOfATrueSoul_TrueSoul_Ring",
	"GOB_DrowCommander_Leather_Boots",
	"UNI_Leather_Halsin",
	"UNI_Halsin_Gloves",
	"ACT1_HAG_HagMask",
	-- "HAG_SwampedHero_OldFancyHelmet",
	"UND_DrowDisguiseCowl",
	-- "MAG_Paladin_MomentumOnConcentration_Boots",
	"CRE_Crest_Abbot",
	"TWN_Tollhouse_TradersRing",
	"MAG_ChargedLightning_StaticDischarge_Amulet",
	"SHA_SandthiefsRing",
	"LOW_GuildRing",
	"MAG_Psychic_PsychicFeedback_Armor",
	"MAG_Psychic_Staggering_Amulet",
	"MAG_Psychic_TempHP_Ring",
	-- "SCL_SpidersLyre",
	"LOW_PendulumOfMalagard",
	-- "MAG_Illithid_CharmPerson_Ring",
	-- "MAG_Illithid_MindTax_Amulet",
	"QUEST_LOW_Bhaal_Amulet",
	-- "MAG_PHB_Ring_Of_Protection",
	-- "MAG_LC_Lorroakan_Robe",
	-- "MAG_WYRM_SleepImmunity_Amulet",
	"UNI_OrpheusChains_Helmet",
	"UNI_OrpheusChains_Gloves",
	"WYR_MonkAmulet_Amulet_NoGhost",
	"UNI_LOW_SteelWatchFoundry_ExplodingCollar",
	-- "UNI_ARM_OfGiantHillStrength_Gloves",
	"QUEST_WYR_RestoredMagicRing",
	-- "MAG_Oathbreaker_Boots",
	-- "MAG_Oathbreaker_Gloves",
	-- "MAG_Oathbreaker_Helmet",
	-- "MAG_Oathbreaker_Platemail",
	-- "MAG_OfGreaterSorcery_Amulet",
	"MAG_Illithid_Carapace_Boots",
	"WPN_Warhammer_Azer",
	"WPN_Djinni_Scimitar_PlanarAlly",
	"WPN_Quaterstaff_Dryad_ConjureWoodlandBeings",
	"MAG_Druid_Magic_StuddedLeather_Armor",
	"WPN_Mace_Deva",
	"WPN_Glaive_Cambion",
	"WPN_Shortbow_Skeleton_AnimateDead",
	"MAG_BarbMonk_Cloth_B_1",
	"MAG_BarbMonk_Cloth_A_1",
	"MAG_BarbMonk_Cloth_A_2_Late",
	"MAG_BarbMonk_Cloth_Hat_A_2_Late",
	"MAG_BarbMonk_Cloth_Hat_A_1",
	"MAG_Druid_Magic_Leather_Armor",
	"MAG_EndGameCaster_Circlet",
	"ARM_Robe_Selunite",
	"UNI_LOW_KiamGodasKilatDrum",
	"UNI_LOW_DostrealtsPiccolo",
	"UNI_LOW_StolyarofsTableLute",
	"UNI_LOW_FalataericCliLyre",
	"UNI_LOW_GlimmergadSelgauntFiddle",
	"MAG_Toll_Collector_Cloak",
	-- "WPN_Battleaxe",
	-- "WPN_Club",
	-- "WPN_Flail",
	-- "WPN_Glaive",
	-- "WPN_Greataxe",
	-- "WPN_Greatclub",
	-- "WPN_Greatsword",
	-- "WPN_Handaxe",
	-- "WPN_HandCrossbow",
	-- "WPN_HeavyCrossbow",
	-- "WPN_Javelin",
	-- "WPN_LightCrossbow",
	-- "WPN_LightHammer",
	-- "WPN_Longbow",
	-- "WPN_Longsword",
	-- "WPN_Mace",
	-- "WPN_Maul",
	-- "WPN_Morningstar",
	-- "WPN_Pike",
	-- "WPN_Quarterstaff",
	-- "WPN_MagicStaff",
	-- "WPN_Dagger_Shar",
	-- "WPN_Scimitar_Shar",
	-- "WPN_Shortbow",
	-- "WPN_Shortsword",
	-- "WPN_Sickle",
	-- "WPN_Spear",
	-- "WPN_Trident",
	-- "WPN_Warhammer",
	-- "WPN_WarPick",
	"WPN_Halberd_1",
	"WPN_Rapier_1",
	"WPN_Scimitar_1",
	"WPN_Dagger_2",
	"WPN_Halberd_2",
	"WPN_Rapier_2",
	"WPN_Scimitar_2",
	"WPN_Dagger_B",
	"WPN_Dagger_C",
	"WPN_MeatCleaver",
	"WPN_Pitchfork",
	"WPN_Torch_StartLit",
	-- "WPN_ToySword",
	"WPN_Salami",
	"WPN_Scimitar_FlameBlade",
	"WPN_MinePickaxe",
	"WPN_WhippingCane",
	"WPN_Automaton_Halberd",
	"WPN_Bugbear_Morningstar",
	"WPN_Goblin_Greatclub",
	"WPN_Goblin_BrandingTool",
	"WPN_Gnoll_Spear",
	"WPN_Gnoll_Bow",
	"WPN_Harpy_Club",
	"WPN_Imp_Sickle",
	"WPN_Imp_Handaxe",
	"WPN_Imp_Scimitar",
	"WPN_Imp_LightCrossbow",
	"WPN_Imp_Shortsword",
	"WPN_Kuotoa_Spear",
	"WPN_Kuotoa_LightCrossbow",
	"WPN_Redcap_Sickle",
	"WPN_Redcap_Staff",
	"WPN_WoodWoad_Club",
	"WPN_Rapier_Pact",
	"WPN_Dagger_Rusty",
	"WPN_Halberd_Rusty",
	"WPN_Rapier_Rusty",
	"WPN_Scimitar_Rusty",
	"WPN_Torch_Blue",
	"WPN_Torch_Green",
	"WPN_Torch_Purple",
	"WPN_Meazel_Shortsword",
	"WPN_SkullFlail",
	"WPN_Leech",
	"WPN_Syringe",
	"WPN_Trepan",
	"WPN_Lantern",
	"WPN_Quaterstaff_Mindflayer",
	"WPN_Sahuagin_Spear_A",
	"WPN_Sahuagin_Spear_B",
	"WPN_Sahuagin_Longbow",
	"WPN_DeathKnight_Longsword",
	"WPN_Djinni_Scimitar",
	"WPN_Quaterstaff_Dryad",
	"WPN_Scimitar_Fire_Myrmidon",
	"HAG_SwampedHero_OldFancyGreatsword",
	"PLA_WPN_DreadedSkullsFlail",
	"UND_SharranCrossbow",
	"UNI_NarrativeLoot_SilverDagger",
	"MAG_LowHP_IncreaseDamagePsychic_GithShortsword",
	"MAG_LowHP_IncreaseDamagePsychic_GithLongsword",
	"MAG_LowHP_IncreaseDamagePsychic_GithHeavyCrossbow",
	"MAG_Fire_BurningDamage_Longsword",
	"Quest_SCL_Moonblade",
	"Quest_SCL_Eclipseblade",
	"TWN_SharDagger",
	"HAV_SpearOfSelune",
	"WPN_ShadowBlade",
	"HAV_MAG_ShadowRending_Dagger",
	"MAG_Psychic_MentalSundering_Dagger",
	"LOW_OskarsBeloved_TorchOfTrueRevocation",
	"LOW_RamazithsTower_Nightsong_Silver_Sword",
	"MAG_Surgeon_Bonesaw",
	"MAG_Surgeon_Leech",
	"MAG_Surgeon_Syringe",
	"MAG_Surgeon_Trepan",
	"MAG_Bloodsoaked_Greataxe",
	"MAG_LC_Jannath_Hat",
	"UNI_PLA_SmugglersRing",
	-- "MAG_WYR_Orin_Bhaalist_Dagger",
	"MAG_BG_Sarevok_OfChaos_Greatsword_NoPassives",
	"MAG_Vicious_Shortsword",
	"MAG_Infernal_Mace",
	"MAG_Infernal_Spear",
	"MAG_Infernal_Longsword",
	"MAG_Infernal_Warhammer",
	-- "MAG_Bhaalist_Paralyzing_Dagger",
	-- "MAG_TheImpaler_Pike",
	"WYR_Circus_WetCloak",
	"MAG_Zhentarim_BloodfeederBlade_Rapier",
	"UNI_LOW_SzarrRing",
	"UNI_WYR_ExplosiveToy",
	"UNI_WYR_ExplosiveToy_Broken",
	"WYR_ExplosiveToy",
	"WYR_ExplosiveToy_Broken",
	"UNI_PUZ_LOW_HouseOfHope_ExplosiveTeddyBear",
	"PUZ_LOW_HouseOfHope_ExplosiveTeddyBear",
	"PUZ_Trap_Gortash_GrenadeInstantiator_Grenade",
	"WYR_Gortash_Grenade",
	"WPN_Grenade_Orthon_A",
	"OBJ_Bomb_Orthon_override",
	"QUEST_HAV_InfernalGrenade",
	"OBJ_BallBearings",
	"LOW_RegenerationPrevention_Grenade",
	"GLO_CursedIronFlask",
	"GLO_CursedIronFlask_Empty",
	"GLO_DevilishOx_Fruit_Apple",
	-- "ATT items",
	"WPN_Zariel_Flail",
	"WPN_Zariel_Hammer",
	"MOD_WPN_Ranseur",
	"MOD_Prism_Helper_Invisible_A",
	"MOD_Plantear_Greatsword_B",
	"MOD_Meteor_Helper_Invisible_A",
	"MOD_Eladrin_Longbow",
	"MOD_Irenicus_Mace",
	"MOD_Erinyes_Bow",
	"MOD_Erinyes_Longsword",
	"MOD_Runepowder_Time_Bomb",
	"MOD_Runepowder_Vial_Thrown",
	"MOD_RuneVial",
	"LOOT_Throwable_Spell_DelayedBlastFireball",
	"MOD_Whirlwind_Helper",
	"MOD_RevGrav_Helper_Invisible_A",
	"MOD_Helper_Spell_IncendiaryCloud",
	"MOD_Helper_Spell_MaddeningDarkness",
	"MOD_DelayedFireball_Helper_Invisible_A",
	"MOD_Solar_Bow",
	"MOD_Solar_Greatsword",
	"MOD_Icingdeath",
	"MOD_Twinkle",
	"MOD_Drizzt_Scimitar1",
	"MOD_Drizzt_Scimitar2",
	"MOD_BalorVorp",
	"MOD_FireGiant_Sword",
	"MOD_FrostGiant_Axe",
	"MOD_StoneGiant_Club",
	"MOD_StormGiant_Sword",
	"MOD_CloudGiant_Mace",
	"MOD_PitFiend_Mace",
	"MOD_DeadThreeScion_Dagger",
	"MOD_ATT_ShadowBlade",
	"MOD_ATT_FalxBlade",
	"MOD_ATT_RubyRod",
	"MOD_ATT_DispaterRod",
	"MOD_MalebrancheRanseur",
	"MOD_ATT_FiernaBlade",
	"MOD_ATT_BelialRanseur",
	"MOD_LorenzoGlaive",
	"MOD_Whisper",
	"MOD_Helper_Spell_DarkStar",
	"MOD_Helper_Spell_RavenousVoid",
	"MOD_LucienScimitar"
}

for _, name in ipairs(items) do
	table.insert(regex, "^" .. name .. "$")
end

return regex
